/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.gif;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int animated_gif=0x7f020000;
        public static final int beach=0x7f020001;
        public static final int button=0x7f020002;
        public static final int cartoon=0x7f020003;
        public static final int demo=0x7f020004;
        public static final int frog=0x7f020005;
        public static final int games=0x7f020006;
        public static final int gm=0x7f020007;
        public static final int icon=0x7f020008;
        public static final int lion=0x7f020009;
        public static final int music=0x7f02000a;
        public static final int parts=0x7f02000b;
        public static final int rose=0x7f02000c;
        public static final int skiing=0x7f02000d;
        public static final int zipperanimated=0x7f02000e;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
